apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ha9pcpu5y-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-93a9ef8249.ycdh.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:5b93b1020c4799f62b139d7887b6cd2aa509eeb3@sha256:d28281a5975bf1a9b29a3b290732b36550ca976c833af34994efff011bf64c6f
          name: container-image
